site_name: 'TensorFlow.jl'
site_description: 'An interface to TensorFlow'
site_author: 'Jon Malmaud'
repo_name: 'GitHub'
repo_url: 'https://github.com/malmaud/TensorFlow.jl'
copyright: 'Copyright (c) 2016 Jonathan Malmaud'
docs_dir: 'docs/build'
site_dir: 'tfdocs'

pages:
  - Home: index.md
  - Manual:
    - 'MNIST tutorial': tutorial.md
    - 'Visualizing with Tensorboard': visualization.md
    - 'Using queues for loading your data': io.md
    - 'Shape inference": shape_inference.md
  - Reference:
    - 'Core functions': core.md
    - 'Operations': ops.md
    - 'IO pipelines with queues': io_ref.md
  - Examples:
    - 'Basic usage': basic_usage.md
    - 'Logistic regression': logistic.md


theme: 'material'
extra:
  author:
    github: 'malmaud'
  logo: 'images/logo.png'

markdown_extensions:
  - codehilite(css_class=code)
  - admonition

google_analytics:
  - 'UA-1123761-11'
  - 'auto'
